# Fibonacci retracement to identify support level
> Fibonacci trading tools are used for determining support/resistance levels or to identify price targets. Fibonacci numbers work like magic in finding key levels in any widely traded security.

- badges: true
- toc: true
- categories: [personal-finance]
- comments: true

The Fibonacci ratios, 23.6%, 38.2%, and 61.8%, can be applied for time series analysis to find support level. Whenever the price moves substantially upwards or downwards, it usually tends to retrace back before it continues to move in the original direction. 

## Fibonacci sequence
Fibonacci sequence is a series of numbers, starting with zero and one, in which each number is the sum of the previous two numbers.


The Fibonacci sequence is 0, 1, 1, 2, 3, 5, 8, 13, 21, 34……

It extends to infinity and can be summarized as:

In [1]:
# collapse-hide
from IPython.display import display, Math, Latex

display(Math(r"X_n = X_{n-1} + X_{n-2}"))

<IPython.core.display.Math object>

### Interesting facts about the Fibonacci sequence

Divide any number in the sequence by the previous number; the ratio is always approximately 1.618. 1.618 is known as the golden ratio. 

In [2]:
# collapse-hide
from IPython.display import display, Math, Latex

display(Math(r"\frac{X_n}{X_{n-1}} = 1.618"))

<IPython.core.display.Math object>

Similarly, divide any number in the sequence by the next number; the ratio is always approximately 0.618.

In [3]:
# collapse-hide
from IPython.display import display, Math, Latex

display(Math(r"\frac{X_n}{X_{n+1}} = 0.618"))

<IPython.core.display.Math object>

The square root of 0.618 is 0.786.

Similar consistency is found when any number in the sequence is divided by a number two places right to it.

In [4]:
# collapse-hide
from IPython.display import display, Math, Latex

display(Math(r"\frac{X_n}{X_{n+2}} = 0.382"))

<IPython.core.display.Math object>

There is consistency when any number in the sequence is divided by a number three places right to it.

In [5]:
# collapse-hide
from IPython.display import display, Math, Latex

display(Math(r"\frac{X_n}{X_{n+3}} = 0.236"))

<IPython.core.display.Math object>

> Note: The ratios 23.6%, 38.2%, 61.8%, and 78.6% are known as the Fibonacci ratios

## How to find Fibonacci retracement levels?

In [6]:
#hide
%load_ext blackcellmagic

In [7]:
# hide
import trendln
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
import altair as alt
import pandas as pd

tick = yf.Ticker("RELIANCE.NS")
hist = tick.history(period="4y", rounding=True)
price = hist["Close"]

price_min = min(price)
price_max = max(price)

# Fibonacci Levels considering original trend as upward move
diff = price_max - price_min
level1 = np.round(price_max - 0.236 * diff, 2)
level2 = np.round(price_max - 0.382 * diff, 2)
level3 = np.round(price_max - 0.618 * diff, 2)
level4 = np.round(price_max - 0.786 * diff, 2)

In [8]:
# collapse-hide
print("Level \t Price")
print(f"0% \t {price_max}")
print(f"23.6% \t {level1}")
print(f"38.2% \t {level2}")
print(f"61.8% \t {level3}")
print(f"78.6% \t {level4}")
print(f"100% \t {price_min}")

Level 	 Price
0% 	 1609.95
23.6% 	 1336.89
38.2% 	 1167.96
61.8% 	 894.9
78.6% 	 700.52
100% 	 452.91


In [9]:
#collapse-hide
plot_price = alt.Chart(hist.reset_index()).mark_line().encode(x="Date", y="Close")


def plot_overlay(price_level):
    overlay = pd.DataFrame({"Close": [price_level]})
    plot_price_level = (
        alt.Chart(overlay).mark_rule(color="gray", strokeWidth=1).encode(y="Close:Q")
    )
    return plot_price_level


alt.layer(
    plot_price,
    plot_overlay(price_min)
    + plot_overlay(level1)
    + plot_overlay(level2)
    + plot_overlay(level3)
    + plot_overlay(level4)
    + plot_overlay(price_max),
).interactive().properties(width=600, height=300)

alt.LayerChart(...)

## Using Fibonacci retracement trading strategy

The retracement levels can be used in a situation where you wanted to buy a particular stock but you have not been able to because of a sharp run-up in the stock price. In such a situation, wait for the price to correct to Fibonacci retracement levels such as 23.6%, 38.2%, and 61.8% and then buy the stock. The ratios **38.2%** and **61.8%** are the most important support levels.

This Fibonacci retracement trading strategy is more effective over a longer time interval and like any indicator, using the strategy with other technical indicators such as RSI, MACD, and candlestick patterns can improve the probability of success.